version: '3.8'

services:
  appwrite:
    image: appwrite/appwrite:latest
    container_name: appwrite
    restart: always
    ports:
      - 3000:80
    volumes:
      - ./appwrite:/storage
      - /var/run/docker.sock:/var/run/docker.sock  

  mysql:
    image: mysql:5.7
    container_name: appwrite-mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=appwrite
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: