name: Render Deployment Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Trigger Render Deploy Hook
        run: |
          curl -f -X POST "${{ secrets.RENDER_DEPLOY_HOOK }}"
